import re

REGEX_NWORD_HARDR = re.compile(
    r"\b(n*[1i!l]+[g9]{2,}[3e]+[r5]+s*)", re.IGNORECASE)
REGEX_NWORD = re.compile(r"\b(n*[1i!l]+[g9]{2,}[a4]+s*)", re.IGNORECASE)
DRAMA_LLAMA = re.compile(r"(?:l+|d+r+)a+m+a", re.IGNORECASE)
NWORD = "🇳 🇼 🇴 🇷 🇩"
GIRLS = [
    re.compile(r"\bs+?l+?a+?y+?\b", re.IGNORECASE),
    re.compile(r"\bg+?i+?v+?i+?n+?g+?\b", re.IGNORECASE),
    re.compile(r"\bq+?u+?e+?e+?n+?\b", re.IGNORECASE),
    re.compile(r"\by+?a+?s+?s*?\b", re.IGNORECASE),
    re.compile(r"\bthe\s+girls\s+are(n't)?\s+.*?\b", re.IGNORECASE),
    re.compile(r"\bs+?n+?a+?t+?c+?h+?e+?d+?\b", re.IGNORECASE),
    re.compile(r"\bl+?i+?t+?\b", re.IGNORECASE),
    re.compile(r"\bb+?a+?e+?\b", re.IGNORECASE),
    re.compile(r"\bg+?o+?a+?l+?s+?\b", re.IGNORECASE),
    re.compile(r"\bs+?q+?u+?a+?d+?\b", re.IGNORECASE),
    re.compile(r"\bf+?i+?r+?e+?\b", re.IGNORECASE),
    re.compile(r"\bt+?e+?a+?\b", re.IGNORECASE),
    re.compile(r"\bg+?o+?\s+o+?f+?f+?\b", re.IGNORECASE),
    re.compile(r"\bp+?o+?p+?\s+o+?f+?f+?\b", re.IGNORECASE),
    re.compile(r"\bp+?e+?r+?i+?o+?d+?\b", re.IGNORECASE),
    re.compile(r"\bg+?i+?r+?l+?\s+.*?\b", re.IGNORECASE),
    re.compile(r"\bf+?l+?e+?e+?k+?\b", re.IGNORECASE),
    re.compile(r"\bs+?i+?s+?t+?e+?r+?s+?\b", re.IGNORECASE),
    re.compile(r"\bt+?h+?i+?c+?c+?\b", re.IGNORECASE),
    re.compile(r"\bd+?i+?c+?k+?\b", re.IGNORECASE),
]

BRITISH = [
    re.compile(r"\bb+?e+?v+?v+?y+?\b", re.IGNORECASE),
    re.compile(r"\bb+?e+?v+?\b", re.IGNORECASE),
    re.compile(r"\bb+?i+?r+?d+?\b", re.IGNORECASE),
    re.compile(r"\bb+?l+?i+?m+?e+?y+?\b", re.IGNORECASE),
    re.compile(r"\bb+?l+?o+?o+?d+?y+?\b", re.IGNORECASE),
    re.compile(r"\bb+?o+?g+?\b", re.IGNORECASE),
    re.compile(r"\bb+?o+?g+?\s+r+?o+?l+?l+?\b", re.IGNORECASE),
    re.compile(r"\bb+?o+?n+?k+?e+?r+?s+?\b", re.IGNORECASE),
    re.compile(r"\bb+?u+?z+?z+?i+?n+?g+?\b", re.IGNORECASE),
    re.compile(r"\bc+?a+?n+?t+?\s+b+?e+?\s+a+?r+?s+?e+?d+?\b", re.IGNORECASE),
    re.compile(r"\bc+?h+?a+?v+?\b", re.IGNORECASE),
    re.compile(r"\bc+?h+?e+?e+?k+?y+?\b", re.IGNORECASE),
    re.compile(r"\bc+?h+?u+?f+?f+?e+?d+?\b", re.IGNORECASE),
    re.compile(r"\bc+?o+?c+?k+?\s+u+?p+?\b", re.IGNORECASE),
    re.compile(r"\bc+?r+?a+?c+?k+?i+?n+?g+?\b", re.IGNORECASE),
    re.compile(r"\bc+?u+?p+?p+?a+?\b", re.IGNORECASE),
    re.compile(r"\bd+?a+?f+?t+?\b", re.IGNORECASE),
    re.compile(r"\bd+?o+?d+?g+?y+?\b", re.IGNORECASE),
    re.compile(r"\bf+?a+?f+?f+?i+?n+?g+?\s+a+?r+?o+?u+?n+?d+?\b", re.IGNORECASE),
    re.compile(r"\bf+?i+?v+?e+?r+?\b", re.IGNORECASE),
    re.compile(r"\bg+?i+?t+?\b", re.IGNORECASE),
    re.compile(r"\bg+?o+?b+?s+?m+?a+?c+?k+?e+?d+?\b", re.IGNORECASE),
    re.compile(r"\bg+?r+?a+?f+?t+?i+?n+?g+?\b", re.IGNORECASE),
    re.compile(r"\bk+?e+?r+?f+?u+?f+?f+?l+?e+?\b", re.IGNORECASE),
    re.compile(r"\bk+?n+?a+?c+?k+?e+?r+?e+?d+?\b", re.IGNORECASE),
    re.compile(r"\bl+?a+?d+?\b", re.IGNORECASE),
    re.compile(r"\bl+?o+?s+?t+?\s+t+?h+?e+?\s+p+?l+?o+?t+?\b", re.IGNORECASE),
    re.compile(r"\ble+?g+?\s+i+?t+?\b", re.IGNORECASE),
    re.compile(r"\bm+?i+?n+?g+?i+?n+?g+?\b", re.IGNORECASE),
    re.compile(r"\bm+?u+?g+?\b", re.IGNORECASE),
    re.compile(r"\bm+?u+?p+?p+?e+?t+?\b", re.IGNORECASE),
    re.compile(r"\bn+?i+?c+?k+?\b", re.IGNORECASE),
    re.compile(r"\bp+?i+?e+?d+?\s+o+?f+?f+?\b", re.IGNORECASE),
    re.compile(r"\bp+?i+?s+?s+?e+?d+?\b", re.IGNORECASE),
    re.compile(r"\bp+?l+?a+?s+?t+?e+?r+?e+?d+?\b", re.IGNORECASE),
    re.compile(r"\bp+?r+?o+?p+?e+?r+?\b", re.IGNORECASE),
    re.compile(r"\bs+?k+?i+?n+?t+?\b", re.IGNORECASE),
    re.compile(r"\bs+?l+?a+?g+?\s+o+?f+?f+?\b", re.IGNORECASE),
    re.compile(r"\bs+?o+?d+?\b", re.IGNORECASE),
    re.compile(r"\bt+?a+?k+?i+?n+?g+?\s+t+?h+?e+?\s+p+?i+?s+?s+?\b",re.IGNORECASE),
    re.compile(r"\bt+?e+?n+?n+?e+?r+?\b", re.IGNORECASE),
    re.compile(r"\bt+?h+?r+?o+?w+?i+?n+?g+?\s+a+?\s+w+?o+?b+?b+?l+?y+?\b", re.IGNORECASE),
    re.compile(r"\bt+?r+?o+?l+?l+?i+?e+?d+?\b", re.IGNORECASE),
    re.compile(r"\bb+?l+?o+?k+?e+?\b", re.IGNORECASE),
    re.compile(r"\be+?l+?l+?o+?\b", re.IGNORECASE),
    re.compile(r"\bt+?e+?a+?\b", re.IGNORECASE),
    re.compile(r"\bc+?r+?u+?m+?p+?e+?t+?s+?\b", re.IGNORECASE),
    re.compile(r"\bd+?a+?r+?l+?i+?n+?g+?\b", re.IGNORECASE),
    re.compile(r"\bg+?a+?n+?d+?e+?r+?\b", re.IGNORECASE),
    re.compile(r"\bp+?o+?s+?h+?\b", re.IGNORECASE),
    re.compile(r"\bb+?l+?i+?g+?h+?t+?y+?\b", re.IGNORECASE),
    re.compile(r"\bb+?e+?n+?d+?e+?r+?\b", re.IGNORECASE),
    re.compile(r"\bt+?o+?s+?s+?e+?r+?\b", re.IGNORECASE),
    re.compile(r"\bw+?a+?n+?k+?e+?r+?\b", re.IGNORECASE),
    re.compile(r"\bb+?u+?g+?g+?e+?r+?\b", re.IGNORECASE),
    re.compile(r".+\bl+?o+?v+?e+?\b[.,!?]*$", re.IGNORECASE),
    re.compile(r"\bi+?n+?n+?i+?t+?\b", re.IGNORECASE),
]