// src/tracking/gifs.ts

// Backing logic for /gif: add, list and remove reply GIFs in the slur pool of
// the global responses.json. The rules are pure functions taking and returning
// the whole parsed file, so they are covered by the smoke test and so unknown
// top-level keys (notably _comment) survive an edit.

import { RESPONSES_FILE, ResponseReply } from "@/tracking/responses";
import { loadWords } from "@/tracking/words";
import { loadData, saveData } from "@/utils/file";
import { createLogger } from "@/utils/log";

const log = createLogger("tracking/gifs");

/** Config scope /gif reads and writes: always the global one, never per guild. */
export const GIF_SCOPE = "global";

/** The words.json type whose reply pool /gif manages. */
export const GIF_TYPE = "slur";

/** Category tag meaning "every word of the type", mirroring `poolFor`. */
export const GENERIC = "generic";

/** Ceiling per category, so a command open to everyone cannot flood a pool. */
export const MAX_PER_CATEGORY = 25;

/** A reply entry in object form, as /gif writes them. */
export interface GifEntry {
  /** The GIF link to reply with. */
  content: string;
  /** Word categories this reply applies to. */
  categories?: string[];
  /** Short unique id; absent on hand-written entries. */
  id?: string;
  /** Discord ID of whoever added it. */
  addedBy?: string;
  /** ISO timestamp of when it was added. */
  addedAt?: string;
}

/**
 * responses.json as loaded from disk. Indexed so top-level keys the command
 * does not understand are carried through a round-trip untouched.
 */
export interface RawResponsesFile {
  types?: Record<string, { responses?: ResponseReply[]; spam?: string }>;
  [key: string]: unknown;
}

/** Outcome of a mutation: the config to save, or why it was refused. */
export type GifResult = { ok: true; config: RawResponsesFile } | { ok: false; reason: string };

/** Everything one add needs, kept explicit so the rules stay pure. */
export interface AddGifInput {
  /** The parsed responses.json to add to. */
  raw: RawResponsesFile;
  /** Category tag for the new entry. */
  category: string;
  /** Categories currently valid, from {@link listCategories}. */
  validCategories: string[];
  /** The GIF link. */
  url: string;
  /** Discord ID of whoever is adding it. */
  addedBy: string;
  /** Short unique id, generated by the caller. */
  id: string;
  /** ISO timestamp, supplied by the caller. */
  addedAt: string;
}

/**
 * Lists the categories a GIF can be filed under: every category declared on
 * the slur words, plus "generic" for a reply that fires on any slur.
 * @param guildId - Discord guild ID, for that guild's compiled word list.
 * @returns Category names, "generic" first then the rest alphabetically.
 */
export function listCategories(guildId: string): string[] {
  const list = loadWords(guildId).typeLists.get(GIF_TYPE)?.list;
  const cats = [...new Set(list ? [...list.category.values()] : [])].sort((a, b) =>
    a.localeCompare(b),
  );
  return [GENERIC, ...cats];
}

/**
 * Checks a URL is something the bot can usefully post.
 * @param url - The candidate URL.
 * @returns `true` for a parseable http(s) link.
 */
export function isValidGifUrl(url: string): boolean {
  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    return false;
  }
  return parsed.protocol === "http:" || parsed.protocol === "https:";
}

/**
 * Reads the managed pool out of a loaded config.
 * @param raw - The parsed responses.json.
 * @returns The reply entries, empty when the type is absent.
 */
function poolOf(raw: RawResponsesFile): ResponseReply[] {
  return raw.types?.[GIF_TYPE]?.responses ?? [];
}

/**
 * Rebuilds a config with a new pool, preserving every other key.
 * @param raw - The config being edited.
 * @param responses - The replacement pool.
 * @returns The config to save.
 */
function withPool(raw: RawResponsesFile, responses: ResponseReply[]): RawResponsesFile {
  const types = { ...(raw.types ?? {}) };
  types[GIF_TYPE] = { ...(types[GIF_TYPE] ?? {}), responses };
  return { ...raw, types };
}

/**
 * Lists the pool as objects, optionally filtered to one category. Plain-string
 * entries count as "generic", the same rule `poolFor` applies.
 * @param raw - The parsed responses.json.
 * @param [category] - Restrict to entries carrying this tag.
 * @returns The matching entries, in file order.
 */
export function listGifs(raw: RawResponsesFile, category?: string): GifEntry[] {
  const entries = poolOf(raw).map<GifEntry>((r) =>
    typeof r === "string" ? { content: r, categories: [GENERIC] } : { ...r },
  );
  if (!category) return entries;
  return entries.filter((e) => (e.categories ?? [GENERIC]).includes(category));
}

/**
 * Adds a GIF to a category, refusing an unknown category, a non-http(s) link,
 * a duplicate within that category, or a category already at
 * {@link MAX_PER_CATEGORY}.
 * @param input - The entry to add and the config to add it to.
 * @returns The config to save, or why it was refused.
 */
export function addGif(input: AddGifInput): GifResult {
  const { raw, category, validCategories, url, addedBy, id, addedAt } = input;

  if (!validCategories.includes(category)) {
    return { ok: false, reason: `"${category}" isn't a category. Pick one from the list.` };
  }
  if (!isValidGifUrl(url)) {
    return { ok: false, reason: "That needs to be an http(s) link." };
  }

  const existing = listGifs(raw, category);
  if (existing.some((e) => e.content === url)) {
    return { ok: false, reason: `That link is already in **${category}**.` };
  }
  if (existing.length >= MAX_PER_CATEGORY) {
    return {
      ok: false,
      reason: `**${category}** is full (${MAX_PER_CATEGORY}) - remove one first.`,
    };
  }

  return {
    ok: true,
    config: withPool(raw, [
      ...poolOf(raw),
      { content: url, categories: [category], id, addedBy, addedAt },
    ]),
  };
}

/**
 * Removes an entry by id. Entries with no id were hand-written into the file
 * and are deliberately not reachable from the command.
 * @param raw - The parsed responses.json.
 * @param id - The entry id to remove.
 * @param userId - Discord ID of whoever is removing.
 * @param canRemoveAny - True for admins, who may remove other people's entries.
 * @returns The config to save, or why it was refused.
 */
export function removeGif(
  raw: RawResponsesFile,
  id: string,
  userId: string,
  canRemoveAny: boolean,
): GifResult {
  const pool = poolOf(raw);
  const index = pool.findIndex((r) => typeof r !== "string" && r.id === id);
  if (index === -1) return { ok: false, reason: "That one isn't in the list any more." };

  const entry = pool[index] as GifEntry;
  if (!canRemoveAny && entry.addedBy !== userId) {
    return { ok: false, reason: "You can only remove GIFs you added." };
  }

  return {
    ok: true,
    config: withPool(
      raw,
      pool.filter((_, i) => i !== index),
    ),
  };
}

/**
 * Loads the global responses.json for editing.
 * @returns The parsed config, or an empty object when the file is absent.
 */
export function loadGifConfig(): RawResponsesFile {
  return loadData<RawResponsesFile>(GIF_SCOPE, RESPONSES_FILE, { soft: true });
}

/**
 * Writes an edited config back to the global responses.json.
 * @param config - The config returned by {@link addGif} or {@link removeGif}.
 */
export function saveGifConfig(config: RawResponsesFile): void {
  saveData(GIF_SCOPE, RESPONSES_FILE, config);
  log.info("saved gif config", { entries: poolOf(config).length });
}
